In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from linear_regression import*

In [2]:
x = np.matrix(np.random.randn(16).reshape(4,4))
y = np.matrix(np.random.randn(4).reshape(4,1))

In [3]:
first = linear_regression()

In [4]:
first.fit(x,y)

(4, 4)


In [5]:
x.shape[1]

4

In [5]:
mean_data = x.mean(axis = 1)

In [19]:
some = (x[:,1] - mean_data)/std_data

In [13]:
std_data = x.std(axis = 1)

In [14]:
std_data

matrix([[ 0.57097036],
        [ 0.29744591],
        [ 0.45102305],
        [ 0.33659371]])

In [16]:
nor = np.zeros(x.shape)

In [17]:
nor

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [21]:
nor[:,1] = some.reshape(4)

In [22]:
nor

array([[ 0.        ,  0.91556187,  0.        ,  0.        ],
       [ 0.        ,  0.43069376,  0.        ,  0.        ],
       [ 0.        ,  0.91846378,  0.        ,  0.        ],
       [ 0.        ,  1.43763096,  0.        ,  0.        ]])

In [5]:
sum(x)

matrix([[-0.15392724,  4.38892508, -0.995133  , -0.26221154]])

In [6]:
sum(sum(x))

matrix([[-0.15392724,  4.38892508, -0.995133  , -0.26221154]])

In [7]:
x.sum()

2.9776532951343935

In [5]:
first.history.plot()

AttributeError: 'numpy.ndarray' object has no attribute 'plot'

In [6]:
pd.DataFrame(first.history).plot()

In [7]:
plt.show()

In [5]:
x

matrix([[-1.66930669, -1.03334198, -0.77137538,  2.33080156],
        [-1.00903223, -1.32439958,  1.41516414, -0.72067268],
        [ 0.95446891, -0.80690974, -0.64884259,  2.27760196],
        [-0.56261565, -1.13422659, -1.33468794, -0.07373695]])

In [6]:
x[1]

matrix([[-1.00903223, -1.32439958,  1.41516414, -0.72067268]])

In [8]:
x[:,0].mean()

-0.57162141579006365

In [14]:
y

matrix([[-0.92363451],
        [-0.78089724],
        [-0.25130687],
        [-0.77005717]])

In [57]:
a =[]
for i in c_list:
    new_type = 0
    for j in a:
        if i == j:
            new_type = 0
            break
        else:
            new_type = 1
    if new_type == 1 or a ==[]:
        a.append(i)
            

In [58]:
a

['a', 'c', 'g', 's', 'd']

In [64]:
combine = np.c_[x,y]

In [68]:
combine = pd.DataFrame(combine)

In [80]:
combine[1].unique()

array([-1.03334198, -1.32439958, -0.80690974, -1.13422659])

In [18]:
c_list = ['a','a','c','g','s','s','d','c']

In [81]:
combine[4] = [1,1,0,0]

In [89]:
data = np.random.randint(0,3,size = 16)

In [91]:
combine.ix[:,:3] = data.reshape(4,4)

In [95]:
grouped = combine.groupby([1,4])

In [104]:
grouped[0].count()

1  4
0  1    2
1  0    1
2  0    1
Name: 0, dtype: int64

In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
data = np.array(iris.data)
target = np.array(iris.target)

In [2]:
from naive_bayesian import*

In [3]:
test = naive_bayesian()

In [4]:
test.fit(data,target)

In [5]:
test.predict(data)

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class '

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
dtype: float64

In [22]:
a.index

Int64Index([1, 2, 3, 4], dtype='int64')

In [24]:
a[1]= 1

In [8]:
b = [1,2,3,4]

In [26]:
for i in b:
    print(a[i])

1.0
nan
nan
nan


In [9]:
b[1]

2

In [6]:
a.ix[[1]]

NameError: name 'a' is not defined

In [2]:
a = pd.DataFrame([1,5,6,2,8])

In [3]:
a

0
0  1
1  5
2  6
3  2
4  8

In [5]:
a =pd.Series([1,5,6,2,1,9])

In [8]:
a[a==a.max()].index

Int64Index([5], dtype='int64')